module.exports = {
  GOALKEEPER: 'Goalkeeper',
  ACROBAT: 'Acrobat',
  STRIKER: 'Striker',
  SWEEPER: 'Sweeper',
  GUARDIAN: 'Guardian',
  SKILLFULTACTICIAN: 'Skillful Tactician',
  TACTICIAN: 'Tactician',
  VICTOR: 'Victor',
  TURTLE: 'Turtle',
  SCORER: 'Scorer',
  PARAGON: 'Paragon',
  FANTASTICVICTOR: 'Fantastic Victor',
  PLAYMAKER: 'Playmaker',
  REDICULOURSWEEPER: 'Ridiculous Sweeper',
  SHOWOFF: 'Show off',
  JUGGLER: 'Juggler',
  SNIPER: 'Sniper',
  CAPABLESWEEPER: 'Capable Sweeper',
}