module.exports = {
  BLACK: 'Black',
  SAFFRON: 'Saffron',
  PINK: 'Pink',
  WHITE: 'Titanium White',
  SIENNA: 'Burnt Sienna',
  ORANGE: 'Orange',
  GREEN: 'Forest Green',
  LIME: 'Lime',
  SKY: 'Sky Blue',
  GREY: 'Grey',
  COBALT: 'Cobalt',
  CRIMSON: 'Crimson',
  PURPLE: 'Purple',
}